<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FestivalRuleSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('festival_rules')->truncate();

        // Helper: build a row array with defaults applied.
        // Keys map directly to the festival_rules columns.
        // All nullable fields default to null unless supplied.
        $rows = [];

        // -----------------------------------------------------------------------
        // MONTHLY RECURRING (any masa, is_recurring = true)
        // -----------------------------------------------------------------------

        // 1. Purnima Vrat
        $rows[] = [
            'slug'             => 'purnima-vrat',
            'name'             => 'Purnima Vrat',
            'type'             => 'vrat',
            'category'         => 'purnima',
            'icon'             => '🌕',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'significance'     => 'Full Moon Tithi. Excellent for Pitru Tarpana and Vishnu Puja. The pinnacle of lunar energy.',
            'rituals'          => json_encode([
                'Sacred bath at dawn',
                'Vishnu-Lakshmi Puja',
                'Moon arghya',
                'Dana (charity)',
                'Pitru Tarpana',
            ]),
            'mantra'           => 'Om Somaya Namah · Om Namo Bhagavate Vasudevaya',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 2. Satyanarayan Vrat
        $rows[] = [
            'slug'             => 'satyanarayan-vrat',
            'name'             => 'Satyanarayan Vrat',
            'type'             => 'vrat',
            'category'         => 'satyanarayan',
            'icon'             => '🪷',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'significance'     => "Lord Vishnu's most beloved Purnima vrat. Skanda Purana: bestows all four Purusharthas.",
            'rituals'          => json_encode([
                'Fast until evening',
                'Satyanarayan Katha recitation',
                'Panchamrit Abhisheka',
                'Offer Tulsi and yellow flowers',
                'Distribute Sheera Prasad',
            ]),
            'mantra'           => 'Om Namo Bhagavate Vasudevaya · Om Shri Satyanarayanaya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 3. Amavasya
        $rows[] = [
            'slug'             => 'amavasya',
            'name'             => 'Amavasya',
            'type'             => 'vrat',
            'category'         => 'amavasya',
            'icon'             => '🌑',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'significance'     => 'Sun-Moon conjunction. Best day for Pitru Tarpana.',
            'rituals'          => json_encode([
                'Pitru Tarpana with black sesame',
                'Shraddha',
                'Fast',
                'Feed crows and cows',
            ]),
            'mantra'           => 'Om Pitru Devatayai Namah · Tilodakam Svadha Namah Pitribhyah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 4. Pradosh Vrat (both pakshas, tithi 13)
        $rows[] = [
            'slug'             => 'pradosh-vrat',
            'name'             => 'Pradosh Vrat',
            'type'             => 'vrat',
            'category'         => 'pradosh',
            'icon'             => '🔱',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 13,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'significance'     => 'Shiva-Parvati Puja in the 1.5-hour window after sunset (Pradosh Kala).',
            'rituals'          => json_encode([
                'Fast from sunrise until Pradosh Puja',
                'Shiva Abhisheka — milk honey yogurt ghee',
                'Light sesame oil lamp during Pradosh Kala',
                'Offer Bilva leaves Datura and white flowers',
                'Chant Mahamrityunjaya Mantra',
            ]),
            'mantra'           => 'Om Namah Shivaya · Om Tryambakam Yajamahe',
            'details'          => 'Pradosh = 13th Tithi. Shiva performs his Tandava during Pradosh Kala.',
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 5. Masik Shivratri
        $rows[] = [
            'slug'             => 'masik-shivratri',
            'name'             => 'Masik Shivratri',
            'type'             => 'vrat',
            'category'         => 'masik_shivratri',
            'icon'             => '🌙',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 14,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'significance'     => 'Monthly Shiva vrat on Krishna Chaturdashi.',
            'rituals'          => json_encode([
                'Nirjala fast',
                'Rudrabhisheka',
                'Bilva leaves offering',
                'Chant Om Namah Shivaya 108 times',
            ]),
            'mantra'           => 'Om Namah Shivaya · Om Tryambakam Yajamahe',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 6. Sankashti Chaturthi
        $rows[] = [
            'slug'             => 'sankashti-chaturthi',
            'name'             => 'Sankashti Chaturthi',
            'type'             => 'vrat',
            'category'         => 'chaturthi',
            'icon'             => '🐘',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 4,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'significance'     => 'Dedicated to Vighnaharta Ganesha. Liberation from dangers.',
            'rituals'          => json_encode([
                'Fast from sunrise to moonrise',
                'Ganesha Puja with 21 Durva blades',
                'Offer modak and coconut',
                'View the Moon',
            ]),
            'mantra'           => 'Om Gam Ganapataye Namah',
            'details'          => 'Sankashti = Liberation from dangers.',
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 7. Vinayak Chaturthi
        $rows[] = [
            'slug'             => 'vinayak-chaturthi',
            'name'             => 'Vinayak Chaturthi',
            'type'             => 'vrat',
            'category'         => 'chaturthi',
            'icon'             => '🐘',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 4,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'significance'     => 'Monthly Ganesha Puja on Shukla Chaturthi.',
            'rituals'          => json_encode([
                'Ganesha Puja',
                'Offer modak',
                'Durva and red flowers',
                'Do not view the Moon',
            ]),
            'mantra'           => 'Om Gam Ganapataye Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 8. Masik Kalashtami
        $rows[] = [
            'slug'             => 'masik-kalashtami',
            'name'             => 'Masik Kalashtami',
            'type'             => 'vrat',
            'category'         => 'kalashtami',
            'icon'             => '🖤',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 8,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'significance'     => 'Monthly Kaal Bhairav worship.',
            'rituals'          => json_encode([
                'Kaal Bhairav Puja (midnight)',
                'Light mustard oil lamp',
                'Black sesame offerings',
                'Feed dogs (vehicle of Bhairav)',
            ]),
            'mantra'           => 'Om Kala Bhairavaya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 9. Masik Durga Ashtami
        $rows[] = [
            'slug'             => 'masik-durga-ashtami',
            'name'             => 'Masik Durga Ashtami',
            'type'             => 'vrat',
            'category'         => 'durgaashtami',
            'icon'             => '⚔️',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 8,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'significance'     => 'Monthly Durga worship on Shukla Ashtami.',
            'rituals'          => json_encode([
                'Recite Durga Saptashati',
                'Kanya Pujan',
                'Offer red flowers',
                'Havan',
                'Night vigil',
            ]),
            'mantra'           => 'Om Dum Durgayai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // -----------------------------------------------------------------------
        // ANNUAL — MASA-SPECIFIC (is_recurring = false)
        // -----------------------------------------------------------------------

        // 10. Holika Dahan
        $rows[] = [
            'slug'             => 'holika-dahan',
            'name'             => 'Holika Dahan',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🔥',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Phalguna']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => "Holika Dahan — Victory of Prahlada's devotion. Symbol of spring fire festival.",
            'rituals'          => json_encode([
                'Light the Holika bonfire',
                'Circumambulate 3 or 7 times',
                'Offer coconut and new harvest',
                'Chant Narasimha Kavacha',
            ]),
            'mantra'           => 'Om Namo Bhagavate Narasimhaya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 11. Holi (day after Phalguna Purnima)
        $rows[] = [
            'slug'             => 'holi',
            'name'             => 'Holi',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🎨',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Phalguna']),
            'day_of_week'      => null,
            'day_offset'       => 1,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => "Festival of Colours — victory of good over evil. Celebrates Krishna's Raas Lila.",
            'rituals'          => json_encode([
                'Play with natural gulal',
                'Temple visit',
                'Enjoy gujiya and thandai',
            ]),
            'mantra'           => 'Radhe Krishna Radhe Krishna · Om Namo Bhagavate Vasudevaya',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 12. Hanuman Jayanti
        $rows[] = [
            'slug'             => 'hanuman-jayanti',
            'name'             => 'Hanuman Jayanti',
            'type'             => 'festival',
            'category'         => 'jayanti',
            'icon'             => '🐒',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Chaitra']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Lord Hanuman born on Chaitra Purnima in Moola Nakshatra.',
            'rituals'          => json_encode([
                'Full day fast',
                'Chant Hanuman Chalisa 108 times',
                'Offer sindoor and oil',
                'Recite Sundarkanda',
            ]),
            'mantra'           => 'Om Ham Hanumate Namah · Manojavam Marutatulyavegam',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 13. Buddha Purnima
        $rows[] = [
            'slug'             => 'buddha-purnima',
            'name'             => 'Buddha Purnima',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '☸',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Vaishakha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Triple blessing — birth enlightenment and Mahaparinirvana of Gautama Buddha.',
            'rituals'          => json_encode([
                'Visit Buddhist temple',
                'Meditation and mindfulness',
                'Noble silence',
                'Feed the poor',
            ]),
            'mantra'           => 'Buddham Sharanam Gachhami · Dhammam Sharanam Gachhami',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 14. Guru Purnima
        $rows[] = [
            'slug'             => 'guru-purnima',
            'name'             => 'Guru Purnima',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '📿',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Ashadha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Maharishi Veda Vyasa Jayanti — compiler of Vedas Mahabharata and Puranas.',
            'rituals'          => json_encode([
                'Vyasa Puja',
                'Recite Guru Gita',
                'Offer yellow flowers and sweets',
                'Begin new spiritual practice',
            ]),
            'mantra'           => 'Gurur Brahma Gurur Vishnu Gurur Devo Maheshvarah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 15. Rakshabandhan
        $rows[] = [
            'slug'             => 'rakshabandhan',
            'name'             => 'Rakshabandhan',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🧵',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Shravana']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => "Sacred festival of the brother-sister bond. Raksha Mantra from Indra's battle.",
            'rituals'          => json_encode([
                'Tie Rakhi in auspicious muhurta',
                'Brother receives tilak and aarti',
                'Brother gives gift to sister',
            ]),
            'mantra'           => 'Yena Baddho Bali Raja Danavandro Mahabalah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 16. Sharad Purnima / Kojagari
        $rows[] = [
            'slug'             => 'sharad-purnima-kojagari',
            'name'             => 'Sharad Purnima Kojagari',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🌕',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Ashwin']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Brightest Purnima — Lord Krishna performed the Maharaas on this night. Moon in Taurus.',
            'rituals'          => json_encode([
                'Night vigil (Kojagari)',
                'Prepare Kheer and offer to the Moon',
                'Lakshmi Puja',
            ]),
            'mantra'           => 'Om Shreem Mahalakshmyai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 17. Kartik Purnima / Dev Diwali
        $rows[] = [
            'slug'             => 'kartik-purnima-dev-diwali',
            'name'             => 'Kartik Purnima Dev Diwali',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🪔',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Kartik']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'The gods celebrate Diwali — Tripuri Purnima. Shiva slew Tripurasura.',
            'rituals'          => json_encode([
                'Offer 1000 lamps in Varanasi',
                'Shiva Puja',
                'Kartik Deepa Dana',
            ]),
            'mantra'           => 'Om Namah Shivaya · Om Shreem Mahalakshmyai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 18. Dattatreya Jayanti
        $rows[] = [
            'slug'             => 'dattatreya-jayanti',
            'name'             => 'Dattatreya Jayanti',
            'type'             => 'festival',
            'category'         => 'jayanti',
            'icon'             => '✨',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Margashirsha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Lord Dattatreya — the Trimurthi avatar of Brahma Vishnu and Mahesh.',
            'rituals'          => json_encode([
                'Sacred bath',
                'Datt Puja',
                'Recite Guru Charitra',
            ]),
            'mantra'           => 'Om Draam Dattatreyaya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 19. Pausha Purnima
        $rows[] = [
            'slug'             => 'pausha-purnima',
            'name'             => 'Pausha Purnima',
            'type'             => 'vrat',
            'category'         => 'purnima',
            'icon'             => '🌕',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Pausha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Sacred winter Purnima — beginning of Kalpavasa at Prayagraj Kumbh Mela.',
            'rituals'          => json_encode([
                'Sacred bath at Triveni Sangam',
                'Vishnu Puja',
                'Donate sesame seeds',
            ]),
            'mantra'           => 'Om Namo Bhagavate Vasudevaya',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 20. Maghi Purnima
        $rows[] = [
            'slug'             => 'maghi-purnima',
            'name'             => 'Maghi Purnima',
            'type'             => 'festival',
            'category'         => 'purnima',
            'icon'             => '🌕',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Magha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Most sacred bathing day of Magh Mela / Kumbh Mela. Moon in Cancer.',
            'rituals'          => json_encode([
                'Sacred bath at Triveni Sangam',
                'Donate sesame seeds',
                'Vishnu Puja',
            ]),
            'mantra'           => 'Om Maghasnanam Karishyami Sarvapapaharam Shubham',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 21. Bhadra Purnima
        $rows[] = [
            'slug'             => 'bhadra-purnima',
            'name'             => 'Bhadra Purnima',
            'type'             => 'vrat',
            'category'         => 'purnima',
            'icon'             => '🌕',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Bhadrapada']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Bhadrapada Purnima — worship of Matsya Avatar and Pitru Tarpana.',
            'rituals'          => json_encode([
                'Sacred bath',
                'Vishnu Puja',
                'Pitru Tarpana',
            ]),
            'mantra'           => 'Om Namo Bhagavate Vasudevaya',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 22. Diwali / Deepawali
        $rows[] = [
            'slug'             => 'diwali-deepawali',
            'name'             => 'Diwali Deepawali',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🪔',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Kartik']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Festival of Lights — Goddess Lakshmi descends to Earth. Lord Rama returns to Ayodhya.',
            'rituals'          => json_encode([
                'Light 108 lamps',
                'Lakshmi-Ganesha Puja',
                'Rangoli',
                'Chopada Pujan',
                'Fireworks',
            ]),
            'mantra'           => 'Om Shreem Hreem Shreem Mahalakshmyai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 23. Mahalaya Amavasya
        $rows[] = [
            'slug'             => 'mahalaya-amavasya',
            'name'             => 'Mahalaya Amavasya',
            'type'             => 'festival',
            'category'         => 'amavasya',
            'icon'             => '🙏',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Ashwin']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Last and most important day of Pitru Paksha. Tarpana for all ancestors.',
            'rituals'          => json_encode([
                'Sarva Pitru Tarpana',
                'Pinda Dana',
                'Brahmin bhoj',
                'Invocation of Durga',
            ]),
            'mantra'           => 'Om Pitru Tarpayami Svaha',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 24. Shani Jayanti
        $rows[] = [
            'slug'             => 'shani-jayanti',
            'name'             => 'Shani Jayanti',
            'type'             => 'festival',
            'category'         => 'amavasya',
            'icon'             => '♄',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 15,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Vaishakha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Birthday of Shani Dev. Shani Puja alleviates Shani Dosha and Sade Sati.',
            'rituals'          => json_encode([
                'Visit Shani temple',
                'Light mustard oil lamp',
                'Donate black sesame seeds',
            ]),
            'mantra'           => 'Om Sham Shanaischaraya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 25. Maha Shivratri
        $rows[] = [
            'slug'             => 'maha-shivratri',
            'name'             => 'Maha Shivratri',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🌙',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 14,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Phalguna']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => "Shiva's cosmic Jyotirlinga manifested. Rudrabhisheka in four Praharas grants Moksha.",
            'rituals'          => json_encode([
                'Nirjala fast',
                'Rudrabhisheka in four Praharas',
                'Bilva leaves milk honey yogurt ghee',
                'Chant Om Namah Shivaya 108 times per Prahara',
                'All-night vigil',
            ]),
            'mantra'           => 'Om Namah Shivaya · Om Tryambakam Yajamahe',
            'details'          => 'Four Praharas: 1. Sunset–9pm: Milk Abhisheka. 2. 9pm–12am: Curd Abhisheka. 3. 12am–3am: Ghee Abhisheka. 4. 3am–Sunrise: Honey Abhisheka.',
            'vidhi_title'      => 'Maha Shivratri Pujan Vidhi',
            'priority'         => 10,
        ];

        // 26. Karwa Chauth
        $rows[] = [
            'slug'             => 'karwa-chauth',
            'name'             => 'Karwa Chauth',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🌙',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 4,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Kartik']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => "Karwa Chauth — women's Nirjala fast for the long life of their husband.",
            'rituals'          => json_encode([
                'Sargi meal before sunrise',
                'Nirjala fast (no water)',
                'View Moon through sieve at moonrise',
            ]),
            'mantra'           => 'Om Namah Shivayai Sharvannyai Saubhagyam Santati Shubham',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 27. Ganesh Chaturthi
        $rows[] = [
            'slug'             => 'ganesh-chaturthi',
            'name'             => 'Ganesh Chaturthi',
            'type'             => 'festival',
            'category'         => 'chaturthi',
            'icon'             => '🐘',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 4,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Bhadrapada']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Ganesh Chaturthi — beginning of the 10-day grand festival.',
            'rituals'          => json_encode([
                'Install Ganesha idol',
                'Shodashopachara Puja',
                'Offer 21 modaks',
                'Durva and red flowers',
                'Do not view the Moon',
            ]),
            'mantra'           => 'Om Gam Ganapataye Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 10,
        ];

        // 28. Krishna Janmashtami
        $rows[] = [
            'slug'             => 'krishna-janmashtami',
            'name'             => 'Krishna Janmashtami',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🦚',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 8,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Bhadrapada']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Birth festival of Lord Krishna — the eighth avatar of Vishnu. Born at midnight in Mathura prison.',
            'rituals'          => json_encode([
                'Full day fast',
                'Celebrate birth at midnight',
                'Panchamrit Abhisheka',
                'Decorate swing (Jhula)',
                'Hare Krishna Kirtan',
            ]),
            'mantra'           => 'Om Namo Bhagavate Vasudevaya · Hare Krishna Hare Krishna',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 29. Kaal Bhairav Jayanti
        $rows[] = [
            'slug'             => 'kaal-bhairav-jayanti',
            'name'             => 'Kaal Bhairav Jayanti',
            'type'             => 'festival',
            'category'         => 'kalashtami',
            'icon'             => '🖤',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 8,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Margashirsha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Kaal Bhairav Jayanti — guardian deity of Kashi. Sins are absolved.',
            'rituals'          => json_encode([
                'Kaal Bhairav Puja (midnight)',
                'Light mustard oil lamp',
                'Black sesame offerings',
                'Feed dogs',
            ]),
            'mantra'           => 'Om Kala Bhairavaya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 10,
        ];

        // 30. Radha Ashtami
        $rows[] = [
            'slug'             => 'radha-ashtami',
            'name'             => 'Radha Ashtami',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🌸',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 8,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Bhadrapada']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Birthday of Devi Radha — 15 days after Janmashtami.',
            'rituals'          => json_encode([
                'Radha-Krishna Puja',
                'Offer lotus flowers',
                'Recite Radha Ashtottara',
            ]),
            'mantra'           => 'Om Radhikayai Namah · Radhe Radhe',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 10,
        ];

        // 31. Maha Ashtami Navratri
        $rows[] = [
            'slug'             => 'maha-ashtami-navratri',
            'name'             => 'Maha Ashtami Navratri',
            'type'             => 'festival',
            'category'         => 'durgaashtami',
            'icon'             => '⚔️',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 8,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Ashwin', 'Chaitra']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Maha Ashtami — most powerful day of Navratri. Goddess Durga slew Mahishasura.',
            'rituals'          => json_encode([
                'Recite Durga Saptashati',
                'Kanya Pujan',
                'Offer red flowers',
                'Ashtami Havan',
                'Night vigil',
            ]),
            'mantra'           => 'Om Dum Durgayai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 5,
        ];

        // 32. Rama Navami
        $rows[] = [
            'slug'             => 'rama-navami',
            'name'             => 'Rama Navami',
            'type'             => 'festival',
            'category'         => 'jayanti',
            'icon'             => '🏹',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 9,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Chaitra']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Birth festival of Lord Rama — the seventh avatar of Vishnu.',
            'rituals'          => json_encode([
                'Rama Navami vrat',
                'Midday Rama Abhisheka',
                'Recite Ramayana',
                'Chant Rama Raksha Stotram',
            ]),
            'mantra'           => 'Shri Ram Jai Ram Jai Jai Ram',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 33. Sharad Navratri Ghatasthapana
        $rows[] = [
            'slug'             => 'sharad-navratri-ghatasthapana',
            'name'             => 'Sharad Navratri Ghatasthapana',
            'type'             => 'festival',
            'category'         => 'navratri',
            'icon'             => '🌺',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 1,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Ashwin']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Beginning of nine sacred nights — the most important Navratri of the year.',
            'rituals'          => json_encode([
                'Ghatasthapana in auspicious muhurta',
                'Sow barley seeds',
                'Light Akhanda Jyoti',
                '9-day fast',
            ]),
            'mantra'           => 'Om Durgayai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 34. Chaitra Navratri / Hindu New Year
        $rows[] = [
            'slug'             => 'chaitra-navratri-hindu-new-year',
            'name'             => 'Chaitra Navratri Hindu New Year',
            'type'             => 'festival',
            'category'         => 'navratri',
            'icon'             => '🌸',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 1,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Chaitra']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Chaitra Shukla Pratipada = Hindu New Year. Gudi Padwa and Yugadi.',
            'rituals'          => json_encode([
                'Gudi Padwa celebration',
                'Yugadi',
                'Listen to Panchanga reading',
                'Navratri Ghatasthapana',
            ]),
            'mantra'           => 'Om Shaktyai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 35. Vijayadashami / Dussehra
        $rows[] = [
            'slug'             => 'vijayadashami-dussehra',
            'name'             => 'Vijayadashami Dussehra',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🏹',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 10,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Ashwin']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Vijayadashami — Lord Rama slew Ravana. Victory of righteousness.',
            'rituals'          => json_encode([
                'Ravana Dahan (burning effigy)',
                'Shami tree Puja',
                'Ayudha Puja',
                'Wear new clothes',
            ]),
            'mantra'           => 'Jai Shri Ram',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 36. Maha Navami / Ayudha Puja
        $rows[] = [
            'slug'             => 'maha-navami-ayudha-puja',
            'name'             => 'Maha Navami Ayudha Puja',
            'type'             => 'festival',
            'category'         => 'navratri',
            'icon'             => '⚔️',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 9,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Ashwin']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => '9th day of Navratri — Maa Siddhidatri. Worship of tools and weapons.',
            'rituals'          => json_encode([
                'Maa Siddhidatri Puja',
                'Ayudha Puja',
                'Kanya Pujan',
                'Havan',
            ]),
            'mantra'           => 'Om Siddhagandharva Yakshadyair Asurair Amarair Api',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 37. Dhanteras
        $rows[] = [
            'slug'             => 'dhanteras',
            'name'             => 'Dhanteras',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '💰',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 13,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Kartik']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Dhanvantari Trayodashi — most auspicious day to purchase gold and silver.',
            'rituals'          => json_encode([
                'Buy gold silver or utensils',
                'Dhanvantari Puja',
                'Light 13 lamps facing south',
            ]),
            'mantra'           => 'Om Dhanvantaraye Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 10,
        ];

        // 38. Naraka Chaturdashi / Choti Diwali
        $rows[] = [
            'slug'             => 'naraka-chaturdashi',
            'name'             => 'Naraka Chaturdashi',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🪔',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 14,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Kartik']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Lord Krishna slew Narakasura on this day. Choti Diwali.',
            'rituals'          => json_encode([
                'Abhyanga snana before sunrise',
                'Light 14 lamps',
                'Fireworks',
            ]),
            'mantra'           => 'Om Krishnaya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 10,
        ];

        // 39. Govardhan Puja / Annakut
        $rows[] = [
            'slug'             => 'govardhan-puja-annakut',
            'name'             => 'Govardhan Puja Annakut',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '⛰',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 1,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Kartik']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Lord Krishna lifted Govardhan Hill. Offering of 56 dishes (Chhappan Bhog).',
            'rituals'          => json_encode([
                'Govardhan Puja',
                '56 dishes offering',
                'Cow worship',
            ]),
            'mantra'           => 'Govardhanadharaya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 10,
        ];

        // 40. Bhai Dooj / Yama Dwitiya
        $rows[] = [
            'slug'             => 'bhai-dooj-yama-dwitiya',
            'name'             => 'Bhai Dooj Yama Dwitiya',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🤝',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 2,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Kartik']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Yamraj visits his sister Yamuna. Festival of the brother-sister bond.',
            'rituals'          => json_encode([
                "Sister applies tilak on brother's forehead",
                'Share a meal together',
                'Brother gives gift to sister',
            ]),
            'mantra'           => 'Yamaya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 10,
        ];

        // 41. Chhath Puja
        $rows[] = [
            'slug'             => 'chhath-puja',
            'name'             => 'Chhath Puja',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '☀',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 6,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Kartik']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Surya Shashthi — 36-hour Nirjala fast dedicated to the Sun god.',
            'rituals'          => json_encode([
                '36-hour Nirjala fast',
                'Sandhya Arghya — offering water to the setting Sun',
                'Offer Thekua and coconut Prasad',
            ]),
            'mantra'           => 'Om Suryaya Namah · Chhathi Maiya ki Jai',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 42. Prabodhini Ekadashi / Tulasi Vivaha
        $rows[] = [
            'slug'             => 'prabodhini-ekadashi-tulasi-vivaha',
            'name'             => 'Prabodhini Ekadashi Tulasi Vivaha',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🌿',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 11,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Kartik']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => "End of Vishnu's 4-month Yoga Nidra. Tulasi-Shaligram wedding ceremony.",
            'rituals'          => json_encode([
                'Drape Tulasi with red cloth',
                'Shaligram Puja',
                'Conduct wedding ceremony rituals',
            ]),
            'mantra'           => 'Tulasyai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 10,
        ];

        // 43. Akshaya Tritiya
        $rows[] = [
            'slug'             => 'akshaya-tritiya',
            'name'             => 'Akshaya Tritiya',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '✨',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 3,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Vaishakha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Akshaya = never diminishing. One of the 3.5 Swayamsiddha Muhurtas. Sun and Moon in exaltation.',
            'rituals'          => json_encode([
                'Buy gold or silver',
                'Charity (Dana)',
                'Begin new business',
                'Vishnu Puja with Tulasi',
            ]),
            'mantra'           => 'Om Namo Bhagavate Vasudevaya · Om Shreem Mahalakshmyai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 44. Vasant Panchami
        $rows[] = [
            'slug'             => 'vasant-panchami',
            'name'             => 'Vasant Panchami',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '📚',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 5,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Magha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Birthday of Maa Saraswati — goddess of knowledge arts music and wisdom.',
            'rituals'          => json_encode([
                'Wear yellow clothes',
                'Saraswati Puja',
                'Offer yellow flowers and yellow sweets',
                'Vidyarambha Samskara',
            ]),
            'mantra'           => 'Om Aim Sarasvatyai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 45. Ganga Dussehra
        $rows[] = [
            'slug'             => 'ganga-dussehra',
            'name'             => 'Ganga Dussehra',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🌊',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 10,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Jyeshtha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'The day Maa Ganga descended to Earth from Heaven.',
            'rituals'          => json_encode([
                'Ganga Snan (sacred bath)',
                'Offer lamps (Deepa Dana)',
                'Donate 10 items',
            ]),
            'mantra'           => 'Om Gam Gangayai Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 46. Naga Panchami
        $rows[] = [
            'slug'             => 'naga-panchami',
            'name'             => 'Naga Panchami',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🐍',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 5,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Shravana']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Worship of serpent gods. Protection from snakebite and fear.',
            'rituals'          => json_encode([
                'Offer milk to Naga idols',
                'Visit Naga temple',
                'Chant Ashtanaga Stotra',
            ]),
            'mantra'           => 'Om Nagebhyo Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 47. Hariyali Teej
        $rows[] = [
            'slug'             => 'hariyali-teej',
            'name'             => 'Hariyali Teej',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '💚',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 3,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Shravana']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Maa Parvati observed this vrat to attain Lord Shiva. Green festival of monsoon.',
            'rituals'          => json_encode([
                'Nirjala fast',
                'Swing (Jhula) and Teej songs',
                'Parvati-Shiva Puja',
            ]),
            'mantra'           => 'Om Namah Shivaya',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 48. Hartalika Teej
        $rows[] = [
            'slug'             => 'hartalika-teej',
            'name'             => 'Hartalika Teej',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '💚',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 3,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Bhadrapada']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Maa Parvati made Shiva idol from sand and prayed all night to attain him.',
            'rituals'          => json_encode([
                'Nirjala fast',
                'Parvati-Shiva Puja with sand idol',
                'Swing (Jhula)',
            ]),
            'mantra'           => 'Om Namah Shivaya',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 49. Anant Chaturdashi / Ganesh Visarjan
        $rows[] = [
            'slug'             => 'anant-chaturdashi-ganesh-visarjan',
            'name'             => 'Anant Chaturdashi Ganesh Visarjan',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🐘',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 14,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Bhadrapada']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Conclusion of the 10-day Ganesh festival. Grand farewell procession.',
            'rituals'          => json_encode([
                'Grand farewell procession',
                'Anant Bhagwan Puja',
                'Water immersion (Visarjan)',
            ]),
            'mantra'           => 'Ganapati Bappa Morya',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 50. Ratha Saptami
        $rows[] = [
            'slug'             => 'ratha-saptami',
            'name'             => 'Ratha Saptami',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '☀',
            'trigger_type'     => 'tithi',
            'tithi_number'     => 7,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => 'Shukla',
            'masa_filter'      => json_encode(['Magha']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Birthday of Lord Surya (Sun god). Chariot of the Sun.',
            'rituals'          => json_encode([
                'Early morning Sun bath',
                'Sun arghya (water offering)',
                '108 Surya Namaskara',
            ]),
            'mantra'           => 'Om Suryaya Namah',
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // -----------------------------------------------------------------------
        // GREGORIAN (fixed calendar dates — national / international days)
        // -----------------------------------------------------------------------

        // 51. Republic Day
        $rows[] = [
            'slug'             => 'republic-day',
            'name'             => 'Republic Day',
            'type'             => 'festival',
            'category'         => 'national',
            'icon'             => '🇮🇳',
            'trigger_type'     => 'gregorian',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => '01-26',
            'is_recurring'     => false,
            'significance'     => 'Republic Day of India. Constitution came into effect on 26 January 1950.',
            'rituals'          => json_encode([]),
            'mantra'           => null,
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 52. International Women's Day
        $rows[] = [
            'slug'             => 'international-womens-day',
            'name'             => 'International Womens Day',
            'type'             => 'festival',
            'category'         => 'national',
            'icon'             => '👩',
            'trigger_type'     => 'gregorian',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => '03-08',
            'is_recurring'     => false,
            'significance'     => "International Women's Day.",
            'rituals'          => json_encode([]),
            'mantra'           => null,
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 53. Ambedkar Jayanti
        $rows[] = [
            'slug'             => 'ambedkar-jayanti',
            'name'             => 'Ambedkar Jayanti',
            'type'             => 'festival',
            'category'         => 'national',
            'icon'             => '📜',
            'trigger_type'     => 'gregorian',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => '04-14',
            'is_recurring'     => false,
            'significance'     => 'Birth anniversary of Dr. B.R. Ambedkar — architect of the Indian Constitution.',
            'rituals'          => json_encode([]),
            'mantra'           => null,
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 54. Earth Day
        $rows[] = [
            'slug'             => 'earth-day',
            'name'             => 'Earth Day',
            'type'             => 'festival',
            'category'         => 'national',
            'icon'             => '🌍',
            'trigger_type'     => 'gregorian',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => '04-22',
            'is_recurring'     => false,
            'significance'     => 'Earth Day — global environmental awareness day.',
            'rituals'          => json_encode([]),
            'mantra'           => null,
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 55. Independence Day
        $rows[] = [
            'slug'             => 'independence-day',
            'name'             => 'Independence Day',
            'type'             => 'festival',
            'category'         => 'national',
            'icon'             => '🇮🇳',
            'trigger_type'     => 'gregorian',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => '08-15',
            'is_recurring'     => false,
            'significance'     => 'Independence Day of India. India attained independence on 15 August 1947.',
            'rituals'          => json_encode([]),
            'mantra'           => null,
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 56. Gandhi Jayanti
        $rows[] = [
            'slug'             => 'gandhi-jayanti',
            'name'             => 'Gandhi Jayanti',
            'type'             => 'festival',
            'category'         => 'national',
            'icon'             => '🕊',
            'trigger_type'     => 'gregorian',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => '10-02',
            'is_recurring'     => false,
            'significance'     => 'Birthday of Mahatma Gandhi — Father of the Nation.',
            'rituals'          => json_encode([]),
            'mantra'           => null,
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 57. Children's Day
        $rows[] = [
            'slug'             => 'childrens-day',
            'name'             => 'Childrens Day',
            'type'             => 'festival',
            'category'         => 'national',
            'icon'             => '👦',
            'trigger_type'     => 'gregorian',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => '11-14',
            'is_recurring'     => false,
            'significance'     => "Children's Day. Birthday of Pandit Jawaharlal Nehru.",
            'rituals'          => json_encode([]),
            'mantra'           => null,
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 58. Christmas
        $rows[] = [
            'slug'             => 'christmas',
            'name'             => 'Christmas',
            'type'             => 'festival',
            'category'         => 'christian',
            'icon'             => '✝',
            'trigger_type'     => 'gregorian',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => '12-25',
            'is_recurring'     => false,
            'significance'     => 'Christmas — birth of Jesus Christ.',
            'rituals'          => json_encode([]),
            'mantra'           => null,
            'details'          => null,
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // -----------------------------------------------------------------------
        // RANGE-BASED SPECIAL RULE
        // -----------------------------------------------------------------------

        // 59. Pitru Paksha Shraddha (Krishna tithi 1-14, Ashwin masa)
        $rows[] = [
            'slug'             => 'pitru-paksha-shraddha',
            'name'             => 'Pitru Paksha Shraddha',
            'type'             => 'vrat',
            'category'         => 'shraddha',
            'icon'             => '🙏',
            'trigger_type'     => 'tithi',
            'tithi_number'     => null,
            'tithi_range_start'=> 1,
            'tithi_range_end'  => 14,
            'paksha'           => 'Krishna',
            'masa_filter'      => json_encode(['Ashwin']),
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'significance'     => 'Pitru Paksha — the 14-day fortnight for ancestor worship. Shraddha performed on the tithi matching the ancestor\'s death tithi.',
            'rituals'          => json_encode([
                'Pitru Tarpana with black sesame and water',
                'Pinda Dana',
                'Brahmin bhoj',
                'Cow feeding',
                'Crow feeding',
            ]),
            'mantra'           => 'Om Pitru Tarpayami Svaha · Tilodakam Svadha Namah Pitribhyah',
            'details'          => 'Each of the 14 Krishna tithis in Ashwin (1 through 14) is dedicated to ancestors who died on that tithi. The 15th tithi (Amavasya) is Mahalaya — seeded separately.',
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // -----------------------------------------------------------------------
        // SOLAR INGRESS — trigger_type = 'solar_ingress'
        // sun_sign_index: 0=Mesha … 9=Makara … 11=Meena
        // -----------------------------------------------------------------------

        // 60. Lohri — eve of Makar Sankranti (day_offset = -1)
        $rows[] = [
            'slug'             => 'lohri',
            'name'             => 'Lohri',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🔥',
            'trigger_type'     => 'solar_ingress',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => -1,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'sun_sign_index'   => 9,
            'nakshatra_index'  => null,
            'significance'     => 'Winter harvest festival of Punjab and North India. Bonfire worship of Sun and Agni.',
            'rituals'          => json_encode(['Light the bonfire', 'Offer sesame, jaggery, and peanuts', 'Bhangra-Gidda dance']),
            'mantra'           => 'Sundar Mundarie Hoe',
            'details'          => 'Lohri: eve of Makar Sankranti.',
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 61. Thai Pongal (same day as Makar Sankranti)
        $rows[] = [
            'slug'             => 'thai-pongal',
            'name'             => 'Thai Pongal',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🍚',
            'trigger_type'     => 'solar_ingress',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'sun_sign_index'   => 9,
            'nakshatra_index'  => null,
            'significance'     => 'The grandest harvest festival of Tamil Nadu.',
            'rituals'          => json_encode(['Boil rice with milk (Pongal dish)', 'Sun Puja', 'Decorate cows and bulls']),
            'mantra'           => 'Om Suryaya Namah · Pongalo Pongal',
            'details'          => 'Thai Pongal: 4-day festival.',
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 62. Makar Sankranti
        $rows[] = [
            'slug'             => 'makar-sankranti',
            'name'             => 'Makar Sankranti',
            'type'             => 'festival',
            'category'         => 'sankranti',
            'icon'             => '☀',
            'trigger_type'     => 'solar_ingress',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'sun_sign_index'   => 9,
            'nakshatra_index'  => null,
            'significance'     => 'Sun enters Capricorn (Makar). Beginning of Uttarayana.',
            'rituals'          => json_encode(['Ganga Snan (sacred bath)', 'Exchange sesame and jaggery', 'Fly kites', 'Donate Khichdi']),
            'mantra'           => 'Om Suryaya Namah',
            'details'          => 'Makar Sankranti: Pongal (Tamil Nadu), Lohri (Punjab), Bihu (Assam).',
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 63. Baisakhi / Vishu / Rongali Bihu (sun enters Mesha / Aries)
        $rows[] = [
            'slug'             => 'baisakhi-vishu-rongali-bihu',
            'name'             => 'Baisakhi / Vishu / Rongali Bihu',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🌾',
            'trigger_type'     => 'solar_ingress',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'sun_sign_index'   => 0,
            'nakshatra_index'  => null,
            'significance'     => 'Mesha Sankranti — Baisakhi in Punjab (Khalsa Panth founded 1699).',
            'rituals'          => json_encode(['Wear new clothes', 'Temple visit', 'Bihu dance', 'Khalsa Diwan']),
            'mantra'           => 'Om Suryaya Namah',
            'details'          => 'Mesha Sankranti: In 1699 Guru Gobind Singh Ji founded the Khalsa Panth.',
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 64-73. Generic Sankrantis for the remaining 10 solar signs (1-8 and 10-11)
        $rashiNames = [
            0 => 'Mesha', 1 => 'Vrishabha', 2 => 'Mithuna', 3 => 'Karka',
            4 => 'Simha', 5 => 'Kanya', 6 => 'Tula', 7 => 'Vrishchika',
            8 => 'Dhanu', 9 => 'Makara', 10 => 'Kumbha', 11 => 'Meena',
        ];
        foreach (array_merge(range(1, 8), [10, 11]) as $signIdx) {
            $sName = $rashiNames[$signIdx];
            $rows[] = [
                'slug'             => strtolower(str_replace(' ', '-', $sName)) . '-sankranti',
                'name'             => "{$sName} Sankranti",
                'type'             => 'vrat',
                'category'         => 'sankranti',
                'icon'             => '☀',
                'trigger_type'     => 'solar_ingress',
                'tithi_number'     => null,
                'tithi_range_start'=> null,
                'tithi_range_end'  => null,
                'paksha'           => null,
                'masa_filter'      => null,
                'day_of_week'      => null,
                'day_offset'       => 0,
                'gregorian_date'   => null,
                'is_recurring'     => false,
                'sun_sign_index'   => $signIdx,
                'nakshatra_index'  => null,
                'significance'     => "Sun enters {$sName} Rashi.",
                'rituals'          => json_encode(['Sun arghya (water offering to Sun)', 'Sacred bath', 'Brahmin charity']),
                'mantra'           => 'Om Suryaya Namah',
                'details'          => '',
                'vidhi_title'      => null,
                'priority'         => 100,
            ];
        }

        // -----------------------------------------------------------------------
        // NAKSHATRA + DAY-OF-WEEK — trigger_type = 'nakshatra_dow'
        // nakshatra_index: 0=Ashwini … 3=Rohini … 21=Shravana … 26=Revati
        // day_of_week: 0=Sun, 1=Mon … 6=Sat (PHP date('w') convention)
        // -----------------------------------------------------------------------

        // 74. Rohini Vrat — Moon in Rohini (index 3) on Monday (dow 1)
        $rows[] = [
            'slug'             => 'rohini-vrat',
            'name'             => 'Rohini Vrat',
            'type'             => 'vrat',
            'category'         => 'jayanti',
            'icon'             => '🌙',
            'trigger_type'     => 'nakshatra_dow',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => 1,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => true,
            'nakshatra_index'  => 3,
            'sun_sign_index'   => null,
            'significance'     => 'Jain tradition: Moon in Rohini Nakshatra + Monday = Rohini Vrat.',
            'rituals'          => json_encode(['Visit Jain temple', 'Rohini Vrat Katha recitation', 'Fast']),
            'mantra'           => 'Namokar Mahamantra',
            'details'          => '',
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // 75. Thiruvonam / Onam — Moon in Shravana (index 21) + Sun in Simha (index 4)
        $rows[] = [
            'slug'             => 'thiruvonam-onam',
            'name'             => 'Thiruvonam (Onam)',
            'type'             => 'festival',
            'category'         => 'festival',
            'icon'             => '🌺',
            'trigger_type'     => 'nakshatra_dow',
            'tithi_number'     => null,
            'tithi_range_start'=> null,
            'tithi_range_end'  => null,
            'paksha'           => null,
            'masa_filter'      => null,
            'day_of_week'      => null,
            'day_offset'       => 0,
            'gregorian_date'   => null,
            'is_recurring'     => false,
            'nakshatra_index'  => 21,
            'sun_sign_index'   => 4,
            'significance'     => "Kerala's grandest festival. Celebration of King Mahabali's annual visit to Earth.",
            'rituals'          => json_encode(['Pookalam (floral rangoli)', 'Onam Sadya (26-dish feast)', 'Vallam Kali (boat race)']),
            'mantra'           => 'Om Namo Bhagavate Vamanaya',
            'details'          => 'Onam: Moon in Shravana Nakshatra + Sun in Simha Rashi.',
            'vidhi_title'      => null,
            'priority'         => 100,
        ];

        // -----------------------------------------------------------------------
        // Normalise rows: fill missing keys and apply display_group / chip_label
        // -----------------------------------------------------------------------
        $categoryMeta = [
            'purnima'          => ['Purnima',      'Full Moon'    ],
            'satyanarayan'     => ['Purnima',      'Satyanarayan' ],
            'amavasya'         => ['Amavasya',     'New Moon'     ],
            'pradosh'          => ['Shiva',        'Pradosh'      ],
            'masik_shivratri'  => ['Shiva',        'Shivratri'    ],
            'shivratri'        => ['Shiva',        'Shivratri'    ],
            'chaturthi'        => ['Ganesha',      'Chaturthi'    ],
            'kalashtami'       => ['Bhairav',      'Kalashtami'   ],
            'durgaashtami'     => ['Devi',         'Durga Ashtami'],
            'navratri'         => ['Navratri',     'Navratri'     ],
            'ekadashi'         => ['Ekadashi',     'Ekadashi'     ],
            'jayanti'          => ['Jayanti',      'Jayanti'      ],
            'sankranti'        => ['Sankranti',    'Sankranti'    ],
            'shraddha'         => ['Pitru Paksha', 'Shraddha'     ],
            'national'         => ['National',     'National'     ],
            'christian'        => ['Christian',    'Christian'    ],
            'festival'         => ['Festival',     'Festival'     ],
        ];

        $rows = array_map(static function (array $row) use ($categoryMeta): array {
            $meta = $categoryMeta[$row['category']] ?? ['Other', ''];
            return $row + [
                'nakshatra_index' => null,
                'sun_sign_index'  => null,
                'display_group'   => $meta[0],
                'chip_label'      => $meta[1],
            ];
        }, $rows);

        DB::table('festival_rules')->insert($rows);
    }
}
